import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { app } from "../firebaseConfig";
import { getAuth, createUserWithEmailAndPassword, GithubAuthProvider, GoogleAuthProvider, signInWithPopup } from "firebase/auth";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
function Register() {
  const auth = getAuth();
  const router = useRouter();

  const googleProvider = new GoogleAuthProvider();
  const githubProvider = new GithubAuthProvider();

  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  useEffect(() => {
    let token = sessionStorage.getItem("Token");
    if (token) {
      router.push("/home");
    }
  }, []);

  const signUp = () => {
    createUserWithEmailAndPassword(auth, email, password)
      .then((response) => {
        console.log(response.user);
        sessionStorage.setItem("Token", response.user.accessToken);
        router.push("/home");
      })
      .catch((error) => {
        const errorCode = error.code;
        const errorMessage = error.message;
        // ..
      });
  };

  const signUpWithGoogle = () => {
    signInWithPopup(auth, googleProvider).then((response) => {
      sessionStorage.setItem("Token", response.user.accessToken);
      router.push("/home");

      console.log(response.user);
    });
  };

  const signUpWithGithub = () => {
    signInWithPopup(auth, githubProvider).then((response) => {
      sessionStorage.setItem("Token", response.user.accessToken);
      router.push("/home");

      console.log(response.user);
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Firebase Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>R3gister</h1>
        <input
          placeholder="email"
          className={styles.inputBox}
          onChange={(event) => setEmail(event.target.value)}
          value={email}
          type="email"
        />
        <input
          placeholder="password"
          className={styles.inputBox}
          onChange={(event) => setPassword(event.target.value)}
          value={password}
          type="password"
        />
        <button className={styles.button} onClick={signUp}>
          Sign Up
        </button>
        <div className={styles.socialButtons}>
          <button className={styles.button} onClick={signUpWithGoogle}>
            Sign Up With Google
          </button>
          <button className={styles.button} onClick={signUpWithGithub}>
            Sign Up With Github
          </button>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export default Register;
